// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxR9tR9UAa3iEOdJUQcPS5eMZXP4wd0vU',
    appId: '1:294355361521:android:af958d23f6dcd8d23e9350',
    messagingSenderId: '294355361521',
    projectId: 'tramatec-app',
    storageBucket: 'tramatec-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJWkaTYuIKxXD_iA7mq5MdnmgHrYeR5O8',
    appId: '1:294355361521:ios:657731216e18bb4d3e9350',
    messagingSenderId: '294355361521',
    projectId: 'tramatec-app',
    storageBucket: 'tramatec-app.firebasestorage.app',
    iosClientId: '294355361521-sf66vr8vcr5o755l3bsssrcei96avra1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tramatecApp',
  );
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBUWv8fETBsFULzedUoPAWw7RtJKVSmuPg",
    authDomain: "tramatec-app.firebaseapp.com",
    projectId: "tramatec-app",
    storageBucket: "tramatec-app.firebasestorage.app",
    messagingSenderId: "294355361521",
    appId: "1:294355361521:web:5723fbd6b8dbb3493e9350",
    measurementId: "G-2Z9NY5DN3Z"
  );
}
